### ISSUE TITLE
Add "open WOF doc from URL" button

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#1]
If you land on the test page it's blank. So add button at top that says "load WOF place" and accepts URL, to then reload the page with the URL param trick?

**Comment by iandees** [comment]
I think I finally found a decent path on this one.

The default landing page looks like this:

![image](https://user-images.githubusercontent.com/261584/74069283-5747e000-49c3-11ea-9a75-d07ebef237c5.png)

You can enter a WOF ID and it will use data.whosonfirst.org to figure out which repo to load from or you can pass in your own URL if you want to load a specific branch/fork. In either case, it redirects you to the edit page, but now instead of having a WOF ID in the URL it has an entire URL as a parameter:

![image](https://user-images.githubusercontent.com/261584/74069370-a130c600-49c3-11ea-8731-8371ec70a6ef.png)

That URL is loaded to show in the form and make edits. It uses the `wof:repo` property of that doc to decide which repository to make the pull request against.

**Comment by nvkelso** [comment]
I dig it!

The only change I'd make is to layout them top and bottom instead of side by side...

- `ID`
- `URL`

Instead of - `ID` | `URL`

Right now it looks like I should do both fields... Or you could make the find by URL just a button that prompts for the URL value with a dialog?

**Comment by nvkelso** [comment]
It's also confusing that the text in the boxes isn't actually text, so clicking them doesn't do anything.

**Comment by nvkelso** [comment]
we can add `e.g.: ` prefix on the text you have in those boxes and call it good?

**Comment by iandees** [comment]
Adjusted alignment and improved placeholder text:

![image](https://user-images.githubusercontent.com/261584/74196055-1568a500-4c22-11ea-9035-90db5c0fec64.png)

**Comment by thisisaaronland** [comment]
FYI:

* https://github.com/whosonfirst/go-whosonfirst-uri/blob/master/parse.go
* https://github.com/whosonfirst/go-whosonfirst-uri/blob/master/parse_test.go

**Comment by nvkelso** [comment]
@iandees formatting nit: can you add 2 lines of whitespace between the blue button `Find by ID` and the text `Find by URL`, please? Then we can close this out...

**Comment by iandees** [comment]
Ah, [another annoyance](https://stackoverflow.com/questions/46452586/why-is-there-no-vertical-space-between-bootstrap-4-rows) on the Bootstrap 3 -> 4 upgrade. Gave it some bottom margin:

![image](https://user-images.githubusercontent.com/261584/74389807-0c640900-4dc5-11ea-9456-448f2c9d21d0.png)

**Comment by nvkelso** [comment]
Works for me :)
