### ISSUE TITLE
Exportify docs as part of export button

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#15]
- [x] Stand up python Exportify as micro service in Nextzen
- [x] Large docs like Norway fail timeout
- [x] Take Export JSON doc and validate it with Exportify microservice
- [x] Present exportified JSON to user
- [x] Python 3 all the Mapzen requirements

**Comment by nvkelso** [comment]
@iandees Can you update this issue, I think most of these are done now?

**Comment by iandees** [comment]
The form now performs an exportify before sending content to GitHub for a PR or downloading.

I increased the timeout on the endpoint from 6 to 15 seconds, which should help with processing larger documents. (4b5b4f3)

There is now a button to download the exportified JSON to the user's computer instead of creating a PR in GitHub. This option doesn't require a GitHub login.

Aaron merged my PRs that py3-ify all the WOF dependencies, so we should be good to go with the last checkbox, too. (465e226)

**Comment by nvkelso** [comment]
Working for me :)
