### ISSUE TITLE
Github integration

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#18]
- [x] Github oauth app
- [x] WOF editor oauth login
- [x] PR making

**Comment by iandees** [comment]
With 282dbe2 I'm able to create pull request (and a fork if one doesn't already exist) that adds a file. Right now it's pointed at someone's test repository, creating a new file instead of modifying an existing one.

Next steps for this:
- Use real-world data:
  - Use the WOF document to calculate **which repo** to create a pull request against and **which file to update**.
  - Receive the exportified JSON and use it as the content of the file.
- Use a better branch name, pull request title, and pull request description.

**Comment by iandees** [comment]
The deployed app will now determine the GitHub repo to use based on the `wof:repo_name` property or build the repo name based on `wof:placetype` and `wof:country`.

Once it finds a repo name, it will try to make a branch in that repo. If it can't make a branch in that repo because you aren't a contributor, it will create a fork and create the branch there.

Once the branch is created, it will update the file on that branch with a single commit.

Once the commit is made to that branch, it will open a pull request that merges the branch into `master` on the WOF repo.

Assuming all that is successful, it will redirect the user to that created pull request after clicking the "Propose changes" button on the WOF editor.

**Comment by nvkelso** [comment]
`Propose changes`, nice :) 

Might be worth some helper text on the button or note below the button?

**Comment by iandees** [comment]
I added a new button that lets you export the changes without making a PR and some help text below the buttons:

![image](https://user-images.githubusercontent.com/261584/73798113-88cc6b80-4777-11ea-8566-b657641b7439.png)

**Comment by nvkelso** [comment]
Both of these work for me now, huzzah!

(I'll followup with minor problems in new issues.)
