### ISSUE TITLE
Update validation logic upstream in exportify for mz:is_current and other ints

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#4]
When we exportify we need to set some values to ints (not JS default strings).

See: https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L127-L140

**Comment by nvkelso** [comment]
See also:

- `mz:is_funky`
- `mz:hierarchy_label`

**Comment by nvkelso** [comment]
Please also remember to update the VERSION (increment minor version).

**Comment by stepps00** [comment]
Any of the `-1`,`0`, or `1` valued `mz` or `wof` property flags that should be encoded as ints should be added to this check. Eventually, the check should be added to the `*-validate` repo, but I'll adjust the exportify check to include relevant properties from:

- https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/mz
- https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/wof

**Comment by stepps00** [comment]
Chatted IRL w @nvkelso, but the `py-mapzen-whosonfirst-export` repo may not be the best place to add property type checks. The existing exportify code only checks types for two property flags that should be in every record. The ask here is to check property types for properties that are not in all WOF records.

I can still update the exportify code, but it might be best to wire these checks in another way.

**Comment by iandees** [comment]
Since these are checks that should happen on all documents before they end up in WOF, not just when editing through the WOF Editor, I think it might be better to put these checks in the `validator` repo, not the `export` repo. But I'm ok with putting them in the WOF editor for now.

**Comment by nvkelso** [comment]
Validated only cries fire, doesn’t fix. So I think for now we fix these in WOF-editor app while general solution is arrived at.

**Comment by stepps00** [comment]
Here's a list of properties that should have integer values of either `-1`, `0`, or `1`. Eventually, these should each be checked in the validate tools, but it seems best for the wof-editor app to handle these check for now (rather than the exportify or validate code):

Optional properties, existing on some WOF records now, each should have int values of `-1`, `0`, or `1`:
  - mz:hierarchy_label_country
  - mz:hierarchy_label_county
  - mz:hierarchy_label_localadmin
  - mz:hierarchy_label_locality
  - mz:hierarchy_label_macrocounty
  - mz:hierarchy_label_macroregion
  - mz:hierarchy_label_region
  - mz:is_approximate
  - mz:is_funky
  - mz:is_hard_boundary
  - mz:is_landuse_aoi
  - mz:is_official
  - wof:megacity
  - wof:statistical_gore

Properties that are written to every record through the Exportify tool, each should have int values of `-1`, `0`, or `1`:
  - mz:is_current
  - mz:hierarchy_label

**Comment by iandees** [comment]
`mz:is_current`, `mz:is_funky`, and `mz:hierarchy_label` are the only items in that list the editor has fields for, and they will now (as of 7e3aa2b22ad5bf19791894ca0dfb701885ee6a5c) check that the value is an integer -1, 0, or 1.

**Comment by nvkelso** [comment]
Working for me, see https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/40/files.

**Comment by stepps00** [comment]
:tada:
