### ISSUE TITLE
¿Hide country codes?

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#6]
¿Should country codes (wof:country, iso:country) be in the form? It's good to see them... but modifying them would also mean moving the file to new Github repo which is completed. So maybe we show but set to read only for now?

**Comment by stepps00** [comment]
Editing country codes is useful, but a more complicated edit because it involves:

- moving the record to a new per-country repo
- removing the record from it's existing per-country repo
- exportifying the record, updating the [`wof:repo`](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/56620097e045ab12d74d54ac19b71e99f0984825/mapzen/whosonfirst/export/__init__.py#L141-L148) property

I agree this should be a "read-only" property to start.

**Comment by iandees** [comment]
I made the `wof:country` a read-only field for now. We can remove it completely from the form if we want.

**Comment by stepps00** [comment]
Cool, and what's the plan for the `iso:country` property going forward?

**Comment by iandees** [comment]
Not sure – does it need to be handled differently? I thought the only concern was `wof:country`.

**Comment by nvkelso** [comment]
I'm fine with `wof:country` read-ony and `iso:country` as editable for now. 

One day when we add repo merging, we can revisit extra logic for keeping iso and wof country in synch (and when to allow them to diverge).

**Comment by nvkelso** [comment]
Talked with @stepps00 more and reopening this to also make `iso:country` read-only for now, please.

**Comment by iandees** [comment]
The `wof:country` and `iso:country` property do the same thing now.
